Repository IrfanAhmadAsqolani/TravelMate_Mobile, pull requests merged in 2022-06, with the labels that each got.

#2 Fix sizing home recommended card is stretched
  lib/features/home_page/pages/views/popular_destination_view.dart
  lib/features/home_page/pages/views/recommended_place_view.dart
  lib/features/home_page/pages/widgets/popular_destination_card.dart
Labels: bug

#5 Add global typography, colors, and components.
  lib/components/components.dart
  lib/components/custom_button.dart
  lib/components/custom_outlined_button.dart
  lib/components/invitation_card.dart
  lib/components/status_chip.dart
  lib/gen/assets.gen.dart
  lib/utils/visual/colors.dart
  lib/utils/visual/typography.dart
Labels: enhancement

#8 Add register UIs
  lib/features/register/pages/register_page.dart
  lib/features/storybook/storybook.dart
Labels: enhancement

#6 Add login UIs
  lib/features/login/pages/login_page.dart
  lib/features/login/pages/widgets/forgot_password_button.dart
  lib/features/login/pages/widgets/widgets.dart
Labels: enhancement

#9 Add detail destinations UIs with new components and route
  lib/components/category_chip.dart
  lib/components/center_title_with_back.dart
  lib/components/components.dart
  lib/dependencies/dependencies.dart
  lib/features/destination_detail/pages/destination_detail_page.dart
  lib/features/home_page/pages/widgets/popular_destination_card.dart
  lib/features/home_page/pages/widgets/recomended_place_card.dart
  lib/utils/routers/routes.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#13 Feature/main page and navbar
  lib/components/custom_button.dart
  lib/components/invitation_card.dart
  lib/features/joined_invitation/pages/joined_invitation_page.dart
  lib/features/login/pages/login_page.dart
  lib/features/main_page/main_page.dart
  lib/features/my_invitation/pages/my_invitation_page.dart
  lib/features/onboarding/pages/onboarding_page.dart
  lib/features/storybook/storybook.dart
  lib/utils/routers/routes.dart
Labels: enhancement

#15 Feature/invitation
  lib/dependencies/dependencies.dart
  lib/features/destination_detail/pages/destination_detail_page.dart
  lib/features/invitation_create/pages/invitation_create_page.dart
  lib/features/invitation_edit/pages/invitation_edit_page.dart
  lib/utils/routers/routes.dart
  lib/utils/visual/input_decoration.dart
  pubspec.yaml
Labels: enhancement

#17 update tampilan invitation detail page
  lib/features/destination_detail/pages/destination_detail_page.dart
  lib/features/invitation_detail/pages/invitation_detail_page.dart
  lib/features/joined_invitation/pages/joined_invitation_page.dart
  lib/features/my_invitation/pages/my_invitation_page.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
Labels: enhancement

#18 Trv bgs3
  lib/features/main_page/main_page.dart
  lib/features/profile/pages/profile.dart
Labels: enhancement

#20 Improvement Interest View, MaxLength, MyInvDetail
  lib/features/invitation_edit/pages/invitation_edit_page.dart
  lib/features/my_invitation_detail/pages/my_invitation_detail_page.dart
  lib/features/onboarding/pages/views/onboarding_interest_view.dart
Labels: enhancement

#24 Add persistent user data when login
  lib/authentication/authentication_manager.dart
  lib/models/users/user_mdl.dart
  lib/network/cache_manager.dart
Labels: enhancement

#25 Modify page and widgets related to destinationMdl about province and category
  lib/features/destination_detail/pages/destination_detail_page.dart
  lib/features/home_page/pages/widgets/popular_destination_card.dart
  lib/features/home_page/pages/widgets/recomended_place_card.dart
  lib/models/category/category.dart
  lib/models/category/category_mdl.dart
  lib/models/destinations/destination_mdl.dart
  lib/models/models.dart
  lib/models/province/province.dart
  lib/models/province/province_mdl.dart
Labels: enhancement

#26 Integrate data in API to My Invitation page
  lib/features/my_invitation/controller/my_invitation_controller.dart
  lib/features/my_invitation/pages/my_invitation_page.dart
  lib/features/my_invitation/pages/views/my_invitation_view.dart
  lib/features/my_invitation/pages/views/views.dart
Labels: enhancement

#27 Add register functionality
  lib/authentication/authentication_manager.dart
  lib/features/login/pages/login_page.dart
  lib/features/register/pages/register_page.dart
  lib/helpers/helpers.dart
  lib/helpers/validation_helper.dart
  lib/models/authentication/authentication.dart
  lib/models/authentication/register_param.dart
Labels: enhancement

#32 Change fromMap to accept int input in destinationMdl
  lib/models/destinations/destination_mdl.dart
Labels: bug-fix

#33 Intergrating Create Invitation with API
  lib/features/destination_detail/pages/destination_detail_page.dart
  lib/features/destination_detail/repositories/destination_detail_repository.dart
  lib/features/invitation_create/controller/invitation_create_controller.dart
  lib/features/invitation_create/pages/invitation_create_page.dart
  lib/features/invitation_detail/controllers/invitation_controller.dart
  lib/features/invitation_detail/pages/invitation_detail_page.dart
  lib/features/invitation_edit/controller/invitation_edit_controller.dart
  lib/models/invitations/params/create_invitation_param.dart
Labels: enhancement

#34 Add upload ktp
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/authentication/authentication_manager.dart
  lib/components/components.dart
  lib/components/verification_status_info.dart
  lib/constants/common_constant.dart
  lib/dependencies/dependencies.dart
  lib/features/home_page/controllers/home_controller.dart
  lib/features/home_page/pages/home_page.dart
  lib/features/invitation_detail/pages/invitation_detail_page.dart
  lib/features/my_invitation_detail/pages/my_invitation_detail_page.dart
  lib/features/onboarding/controllers/file_picker_controller.dart
  lib/features/onboarding/pages/onboarding_page.dart
  lib/features/onboarding/pages/views/onboarding_interest_view.dart
  lib/features/onboarding/pages/views/onboarding_upload_ktp_view.dart
  lib/helpers/auth_helper.dart
  lib/helpers/common_helper.dart
  lib/models/users/user_mdl.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
  pubspec.lock
  pubspec.yaml
Labels: enhancement, dont-merge-yet

#38 bugfixing
  lib/features/invitation_detail/pages/invitation_detail_page.dart
  lib/features/login/pages/login_page.dart
  lib/features/login/pages/widgets/forgot_password_button.dart
  lib/features/login/pages/widgets/widgets.dart
  lib/features/my_invitation_detail/pages/my_invitation_detail_page.dart
  lib/features/register/pages/register_page.dart
  lib/helpers/date_helper.dart
  lib/utils/visual/input_decoration.dart
Labels: bug-fix

#39 add search feature yeay
  lib/features/main_page/main_page.dart
  lib/features/search/controllers/search_controller.dart
  lib/features/search/pages/search_page.dart
Labels: enhancement

#40 Feature/request list
  lib/features/my_invitation_detail/controller/my_invitation_detail_controller.dart
  lib/features/my_invitation_detail/pages/my_invitation_detail_page.dart
  lib/helpers/date_helper.dart
  lib/models/travel_buddy/travel_buddy_mdl.dart
Labels: enhancement

#41 Add Approve Reject
  lib/features/my_invitation_detail/controller/my_invitation_detail_controller.dart
  lib/features/my_invitation_detail/pages/my_invitation_detail_page.dart
Labels: enhancement

#42 bug state invitation detail page
  lib/features/invitation_detail/controllers/invitation_controller.dart
  lib/features/invitation_detail/pages/invitation_detail_page.dart
  lib/features/joined_invitation/pages/views/joined_invitation_view.dart
  lib/features/my_invitation/pages/views/my_invitation_view.dart
  lib/models/travel_buddy/travel_buddy_mdl.dart
Labels: bug-fix, enhancement

#44 Finish profile and error messages
  lib/authentication/authentication_manager.dart
  lib/features/invitation_create/controller/invitation_create_controller.dart
  lib/features/invitation_detail/controllers/invitation_controller.dart
  lib/features/invitation_edit/controller/invitation_edit_controller.dart
  lib/features/profile/pages/controllers/profile_controller.dart
  lib/features/profile/pages/profile.dart
Labels: bug-fix, enhancement

#45 Add slots available counter
  lib/features/invitation_detail/controllers/invitation_controller.dart
  lib/features/invitation_detail/pages/invitation_detail_page.dart
  lib/features/my_invitation_detail/pages/my_invitation_detail_page.dart
  lib/models/invitations/features/invitation_mdl.dart
Labels: enhancement

#46 add safe area search page
  lib/features/search/pages/search_page.dart
Labels: bug-fix

#49 change user open own invitation now go to mydetailinvitationpageroute
  lib/components/invitation_card.dart
Labels: bug-fix

#51 fix bug customer service wont launch
  lib/features/profile/pages/profile.dart
Labels: bug-fix

#52 change limit number to 10
  lib/helpers/validation_helper.dart
Labels: bug-fix
